name: Run pre-commit hooks
on:
  workflow_dispatch:
  pull_request_target:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    environment: elementary_test_env
    steps:
      - name: Checkout Elementary
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.9"

      # mainly needed so mypy will have the dependencies it needs
      - name: Install elementary
        run: pip install -e .

      - name: Install dev requirements
        run: pip install -r dev-requirements.txt

      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure
