name: Test All Warehouse Platforms
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  snowflake:
    uses: ./.github/workflows/test-warehouse.yml
    with:
      warehouse-type: snowflake
    secrets: inherit

  bigquery:
    uses: ./.github/workflows/test-warehouse.yml
    with:
      warehouse-type: bigquery
    secrets: inherit

  redshift:
    uses: ./.github/workflows/test-warehouse.yml
    with:
      warehouse-type: redshift
    secrets: inherit

  databricks:
    uses: ./.github/workflows/test-warehouse.yml
    with:
      warehouse-type: redshift
    secrets: inherit
