name: Update Triage Label
on: issue_comment

permissions:
  issues: write

jobs:
  triage_label:
    if: contains(github.event.issue.labels.*.name, 'awaiting_response')
    runs-on: ubuntu-latest
    steps:
      - name: initial labeling
        uses: andymckay/labeler@master
        with:
          add-labels: "Triage ðŸ‘€"
          remove-labels: "Awaiting Response"
